---
abstract: 'Methods for accessing data collected by a Neurio sensor module.'
author:
  - 'Kedar Warriner'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Neurio
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2.90
  LWP::UserAgent: 6.05
  MIME::Base64: 3.14
version: 0.07
